services:
  postgres:
    image: postgres:latest
    container_name: dbs_postgres

    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=matus
      - POSTGRES_PASSWORD=matus
      - POSTGRES_DB=db
    ports:
      - 5432:5432

  dbszad5:
    build:
      context: .
      dockerfile: ./Dockerfile

    image: dbszad5

    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=matus
      - DATABASE_PASSWORD=matus
      - DATABASE_NAME=db

    depends_on:
      - postgres

    ports:
      - 8000:8000

